apps/multi_track_listening/lib/multi_track_web/router.ex
defmodule MultiTrackWeb.Router do
  use MultiTrackWeb, :router
  alias MultiTrackWeb.Plugs.{RedirectToPublishedMix, LoadMix}

  pipeline :browser do
    if Mix.env() == :prod do
      plug Plug.SSL, rewrite_on: [:x_forwarded_proto]
    end

    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    if Mix.env() == :prod do
      plug Plug.SSL, rewrite_on: [:x_forwarded_proto]
    end

    plug :accepts, ["json"]
  end

  pipeline :mix_common do
    plug LoadMix
    plug RedirectToPublishedMix
  end

  scope "/", MultiTrackWeb do
    pipe_through :browser

    get "/", HomeController, :index

    get "/uploads/:uuid", StorageController, :serve_file

    post "/mixes/create", MixController, :create

    scope "/mixes" do
      pipe_through :mix_common

      get "/:id/track-one", MixController, :new_track_one
      post "/:id/track-one", MixController, :create_track_one
      get "/:id/track-two", MixController, :new_track_two
      post "/:id/track-two", MixController, :create_track_two
      get "/:id/parameters", MixController, :parameters
      put "/:id/parameters", MixController, :create_mix_render
      get "/:id/renders/:render_id", MixController, :mix_render
      post "/:id/renders/:render_id/publish", MixController, :publish
    end

    get "/published/anonymous/:id", PublishedMixController, :show
  end

  scope "/health", MultiTrackWeb do
    get "/", HealthController, :index
  end
end

apps/multi_track_listening/lib/multi_track_listening/published_mixes/published_mix.ex
defmodule MultiTrackListening.PublishedMixes.PublishedMix do
  use Ecto.Schema
  import Ecto.Changeset
  alias MultiTrackListening.Storage
  alias MultiTrackListening.Mixes.{Mix, Render}

  @type t :: %__MODULE__{
          id: integer,
          audio_file: Storage.FileId.t(),
          track_one_name: String.t(),
          track_two_name: String.t(),
          mix: Mix.t() | Ecto.Association.NotLoaded.t(),
          render: Render.t() | Ecto.Association.NotLoaded.t(),
          inserted_at: DateTime.t(),
          updated_at: DateTime.t()
        }

  schema "published_mixes" do
    field :audio_file, :string
    field :track_one_name, :string
    field :track_two_name, :string

    has_one :mix, Mix
    has_one :render, Render

    timestamps()
  end

  @doc false
  def changeset(published_mix, attrs) do
    published_mix
    |> cast(attrs, [:track_one_name, :track_two_name])
    |> validate_required([:track_one_name, :track_two_name])
  end
end

apps/multi_track_listening/lib/multi_track_listening/published_mixes/published_mixes.ex
defmodule MultiTrackListening.PublishedMixes do
  @moduledoc """
  The PublishedMixes context.
  """

  import Ecto.Query, warn: false
  alias MultiTrackListening.Repo

  alias MultiTrackListening.PublishedMixes.PublishedMix

  @doc """
  Returns the list of published_mixes.

  ## Examples

      iex> list_published_mixes()
      [%PublishedMix{}, ...]

  """
  def list_published_mixes do
    Repo.all(PublishedMix)
  end

  @spec get_published_mix(integer) :: PublishedMix.t() | nil
  def get_published_mix(id), do: Repo.get(PublishedMix, id)

  @doc """
  Gets a single published_mix.

  Raises `Ecto.NoResultsError` if the Published mix does not exist.

  ## Examples

      iex> get_published_mix!(123)
      %PublishedMix{}

      iex> get_published_mix!(456)
      ** (Ecto.NoResultsError)

  """
  def get_published_mix!(id), do: Repo.get!(PublishedMix, id)

  @spec create_published_mix_internal(keyword() | %{optional(atom()) => any()}) ::
          PublishedMix.t()
  def create_published_mix_internal(attrs) do
    Ecto.Changeset.change(%PublishedMix{}, attrs) |> Repo.insert!()
  end

  @doc """
  Deletes a PublishedMix.

  ## Examples

      iex> delete_published_mix(published_mix)
      {:ok, %PublishedMix{}}

      iex> delete_published_mix(published_mix)
      {:error, %Ecto.Changeset{}}

  """
  def delete_published_mix(%PublishedMix{} = published_mix) do
    Repo.delete(published_mix)
  end
end

apps/multi_track_listening/lib/multi_track_web/controllers/published_mix_controller.ex
defmodule MultiTrackWeb.PublishedMixController do
  use MultiTrackWeb, :controller

  alias MultiTrackListening.{PublishedMixes, Storage}

  def show(conn, %{"id" => id}) do
    published_mix = %{audio_file: audio_file} = PublishedMixes.get_published_mix!(id)
    audio_url = Storage.file_url(audio_file)
    render(conn, "show.html", mix: published_mix, audio_url: audio_url)
  end
end

apps/multi_track_listening/lib/multi_track_web/views/published_mix_view.ex
defmodule MultiTrackWeb.PublishedMixView do
  use MultiTrackWeb, :view

  def render("scripts.show.html", assigns) do
    render_script_tag(assigns.conn, "mix-card.js")
  end
end

apps/multi_track_listening/lib/multi_track_web/templates/published_mix/mix-card.html.eex
<div class="card published-mix-card">
  <div class="card-header">
    <%= content_tag :p, @mix.track_one_name <> " ✗ " <> @mix.track_two_name,
      class: "card-header-title published-mix-card-title" %>
    <%= if @show_link do %>
      <%= link to: Routes.published_mix_path(@conn, :show, @mix),
        class: "card-header-icon", aria_label: "Mix Page", title: "Mix Page" do %>
        <span class="icon">
          <i class="fa fa-link" aria-hidden="true"></i>
        </span>
      <% end %>
    <% end %>
  </div>
  </header>
  <div class="card-content">
    <div class="published-mix-card-text">
      <p>
        Created by anonymous
      </p>
      <p>
        Please listen with headphones!
      </p>
    </div>
    <%= content_tag :audio, nil,
      class: "published-mix-card-audio",
      controls: true,
      src: @audio_url %>
  </div>
  <footer class="card-footer">
    <%= link "Download", to: @audio_url, download: true,
        class: "card-footer-item" %>
    <%= link "Copy Link", to: "#", class: "card-footer-item",
      data: [mix_card_copy_link: Routes.published_mix_url(@conn, :show, @mix)] %>
  </footer>
</div>

apps/multi_track_listening/lib/multi_track_web/templates/published_mix/show.html.eex
<section class="section">  
  <div class="container">
    <%= render "mix-card.html", Map.put(assigns, :show_link, false) %>
  </div>
</section>